site_name: Tu luyện ngoại ngữ
site_description: Phương pháp học (chắc là) mọi ngoại ngữ thông qua Immersion và Comprehensible Input, completely free.
site_author: duykhanh471


nav:
  - 'Định hướng':
      - 'Trang chủ': 'index.md'
      - 'Tại sao cần tự học?': can-tu-hoc.md
      - 'Trước khi bắt đầu học ngoại ngữ': 'truoc-khi-bat-dau.md'
  - 'Hướng dẫn':
      - 'Hướng dẫn tự hoc': guide.md
      - 'Nghe': nghe.md
      - 'Đọc': doc.md
      - 'Nói': noi.md
      - 'Viết': viet.md
  - 'Anki':
    - 'Tìm hiểu cơ bản về cách học tập và ôn tập Anki': anki.md
    - 'Một bài viết về SRS': 'srs.md'
    - 'Hướng dẫn cài đặt & sử dụng': 'how-to-anki.md'
    - 'Mẹo và kĩ thuật sử dụng': 'ki-thuat-anki.md'
    - '20 quy tắc xây dựng kiến thức': '20rules.md'
  - 'Thiết lập':
      - 'Từ điển': dictionary.md
      - 'Các công cụ hỗ trợ cho việc học': cong-cu.md
  - 'Đầu vào dễ hiểu':
      - 'Tìm hiểu chung': 'comprehensible-input.md'
      - 'Input': input.md
  - 'Immersion':
      - 'Tổng quan': overview.md
      - 'Sentence Mining': sentence-mining.md
  - 'Một số chủ đề khác':
      - 'Timeboxing': timeboxing.md
      - 'Language Domain': language-domain.md
  - 'Tài nguyên tự học':
      - 'Tài nguyên': 'resources.md'
      - 'Từ vựng & Ngữ pháp': 'resource-recommendations.md'
 
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlighting
    - search.share
  name: material

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      
plugins:
  - search
  - open-in-new-tab:
      add_icon: true
  
extra:
  generator: false