site_name: Tu luyện ngoại ngữ - Khu học mở
site_description: Phương pháp học mọi ngoại ngữ thông qua Immersion và Comprehensible Input, completely free.
site_author: duykhanh471


nav:
  - 'Định hướng':
      - 'Trang chủ': 'index.md'
      - 'Tại sao cần tự học?': can-tu-hoc.md
      - 'Trước khi bắt đầu học ngoại ngữ': 'truoc-khi-bat-dau.md'
  - 'Hướng dẫn':
      - 'Hướng dẫn tự hoc': guide.md
      - 'Đọc ngoại ngữ': doc.md
      - 'Nghe ngoại ngữ': nghe.md
      - 'Input': input.md
      - 'SRS': srs.md
  - 'Setup':
      - 'Anki': anki.md
      - 'Từ điển': dictionary.md
      - 'Các công cụ hỗ trợ cho việc học': cong-cu.md
  - 'Comprehensible Input':
      - 'Tìm hiểu về Comprehensible Input': 'comprehensible-input.md'
  - 'Immersion':
      - 'Tổng quan': overview.md
      - 'Sentence Mining': sentence-mining.md
  - 'Một số chủ đề khác':
      - 'Timeboxing': timeboxing.md
      - 'Language Domain': language-domain.md
  - 'Resources':
      - 'Tài nguyên': 'resources.md'
      - 'Từ vựng & Ngữ pháp': 'resource-recommendations.md'
  - 'Recommendations':
      - 'Đọc thêm về các phương pháp học ngoại ngữ': 'recommendations.md'

 
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlighting
    - search.share
  name: material

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      
plugins:
  - search
  # - open-in-new-tab
  
extra:
  generator: false