site_name: Tu luyện ngoại ngữ
site_description: Phương pháp học (chắc là) mọi ngoại ngữ thông qua Immersion và Comprehensible Input, completely free.
site_author: duykhanh471

nav:
  - 'Chuẩn bị hành trang':
      - 'Điểm khởi đầu': 'index.md'
      - 'Tại sao cần tự học ngoại ngữ?': 'phai-tu-hoc.md'
      - 'Trước khi bắt đầu học': 'truoc-khi-bat-dau.md'
  - 'Hướng dẫn học chính':
      - 'Bắt đầu học': 'guide.md'
      - 'Đầu vào dễ hiểu': 'input.md'
      - 'Nghe': nghe.md
      - 'Đọc': doc.md
      - 'Nói': noi.md
      - 'Viết': viet.md
      - 'Hướng dẫn đơn ngữ': 'huong-dan-don-ngu.md'
  - 'Setup':
      - 'Anki': 'anki.md'
      - 'Yomitan': 'yomitan.md'
      - 'Goldendict': 'goldendict.md'
      - 'Hướng dẫn Mining': 'mining.md'
      - 'Xây dựng môi trường ngoại ngữ cho riêng mình': setup.md
  - 'Câu hỏi thường gặp': faq.md
  - 'Hướng dẫn khác':
      - 'Tổng quan về Immersion': overview.md
      - 'Sentence Mining': sentence-mining.md
      - 'Language Domain': language-domain.md
  - 'Tài nguyên học & Gợi ý':
      - 'Tài nguyên': 'resources.md'
 
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlighting
    - search.share
  name: material

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      
plugins:
  - search
  - open-in-new-tab:
      add_icon: true
  
extra:
  generator: false