site_name: Tôi luyện ngoại ngữ - Khu học mở
site_description: Phương pháp học mọi ngoại ngữ thông qua Immersion và Comprehensible Input, completely free.
site_author: duykhanh471
theme:
  name: material
  features:
    - navigation.instant
  palette:
    primary: indigo

nav:
  - 'Trang chủ':
      - 'Khởi đầu': 'index.md'
      - 'Động lực học': 'cai-thien-dong-luc.md'
      - 'Tại sao cần tự học?': can-tu-hoc.md
  - 'Hướng dẫn':
      - 'Bắt đầu tự học': guide.md
      - 'Đọc ngoại ngữ': doc.md
      - 'Đầu vào (Input)': input.md
      - 'Lặp lại ngắt quãng': srs.md
      - 'Vùng ngôn ngữ': language-domain.md
  - 'Lộ trình học':
      - 'Tổng hợp': 'lo-trinh-hoc.md'
  - 'Setup':
      - 'Anki': anki.md
      - 'Kindle': kindle.md
      - 'Từ điển': dictionary.md
      - 'Youtube': youtube.md
  - 'Immersion':
      - 'FAQ': overview.md
  - 'Mining':
      - 'Đào câu': sentence-mining.md
      - 'Timeboxing': timeboxing.md
  - 'Resources':
      - 'Tài nguyên': 'resources.md'
  - 'Recommendations':
      - 'Gợi ý khác': 'recommendations.md'
 
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlighting
    - search.share
  name: material

plugins:
  - open-in-new-tab
  
extra:
  generator: false